"use client";

import { useDeferredValue, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpIcon, ArrowDownIcon } from '@heroicons/react/24/outline';
import { HITTER_STAT_KEYS, HitterPlayer, HitterStats, PITCHER_STAT_KEYS, PitcherPlayer, PitcherStats, PlayerPools, RosterSlot, SortAsc, SortParamHitter, SortParamPitcher } from '@/_lib/types';
import Pagination from '@/components/ui/pagination';

const PAGE_SIZE = 50;


// Generated by AI for filtering via position
const HITTER_FILTER_POSITIONS: RosterSlot[] = ["C", "1B", "2B", "3B", "SS", "CI", "MI", "OF", "U"];

function PositionFilterChips<T extends string>({
  positions,
  selected,
  onToggle,
}: {
  positions: readonly T[];
  selected: T[];
  onToggle: (pos: T) => void;
}) {
  return (
    <div className="flex flex-wrap gap-2 px-3 py-2 bg-gray-700 border-b border-zinc-800">
      {positions.map((pos) => {
        const active = selected.includes(pos);
        return (
          <button
            key={pos}
            onClick={() => onToggle(pos)}
            className={`px-2 py-0.5 rounded text-xs font-semibold border transition-colors ${
              active
                ? "bg-blue-500 border-blue-400 text-white"
                : "bg-gray-600 border-zinc-600 text-zinc-300 hover:border-blue-400 hover:text-white"
            }`}
          >
            {pos}
          </button>
        );
      })}
      {selected.length > 0 && (
        <button
          onClick={() => selected.forEach(onToggle)}
          className="px-2 py-0.5 rounded text-xs font-semibold border border-zinc-600 text-zinc-400 hover:text-white hover:border-zinc-400 transition-colors"
        >
          Clear
        </button>
      )}
    </div>
  );
}


const headerCellClass = "text-center whitespace-nowrap border-r border-zinc-700 last:border-r-0";
const bodyCellClass = "text-white text-center whitespace-nowrap border-r border-zinc-700 last:border-r-0";
const firstHeaderCellClass = "text-left whitespace-nowrap border-r border-zinc-700";
const firstBodyCellClass = "text-white text-left whitespace-nowrap border-r border-zinc-700 font-semibold";
const firstCellStyle = { paddingInline: "0.5rem" };
export default function PlayerTable({ players }  : {players : PlayerPools | null } ) {
  
  /**
   * Search params needed to make sure that sorting is consistent with current state
   */
  const [tab, setTab] = useState<"hitters" | "pitchers">("hitters");

  const tabBar = (
    <div className="flex border-b border-zinc-700">
      {([{key: "hitters", label: "Hitters"}, {key: "pitchers", label: "Pitchers"}] as const).map((keyLabel) => (
        <button
          key={keyLabel.key}
          onClick={() => setTab(keyLabel.key)}
          className={`px-5 py-2 text-sm font-semibold capitalize transition-colors
            ${tab === keyLabel.key
              ? "border-b-2 border-blue-400 text-blue-400"
              : "text-zinc-400 hover:text-white"
            }`}
        >
          {keyLabel.label}
        </button>
      ))}
    </div>
  );

  if (tab === "hitters") {
    return (
      <div className="flex flex-col gap-3">
        {tabBar}
        <HittersTable players={players?.hitters ?? []}/>
      </div>
    );
  } else {
    return (
      <div className="flex flex-col gap-3">
        {tabBar}
        <PitchersTable players={players?.pitchers ?? []}/>
      </div>
    );
  }
}

function SortIcon({ curSort, columnKey, asc }: { curSort: SortParamHitter | SortParamPitcher, columnKey: string, asc: boolean }) {
  if (curSort !== columnKey) return <ArrowDownIcon className="w-4 h-4 text-gray-400" />
  return asc ? <ArrowUpIcon className="w-4 h-4 text-blue-400 font-extrabold"/> : <ArrowDownIcon className="w-4 h-4 text-blue-400 font-extrabold"/>
}

function PitchersTable({ players } : {players : PitcherPlayer[]}) {
  const router = useRouter();

  const [sort, setSort] = useState<{sortParam:SortParamPitcher, asc: SortAsc}>({sortParam: "gp", asc: true});
  const [mlbOnly, setMlbOnly] = useState(false);
  const [page, setPage] = useState(1);
  const deferredMlbOnly = useDeferredValue(mlbOnly);

  

  const sortedPlayers = useMemo(() => {
    function sortPitchers(a : PitcherPlayer,b : PitcherPlayer) {
      let value : number;
      if(sort.sortParam == "name") {
        value = a.name > b.name ? 1 : -1;
      }
      else if(sort.sortParam == "team") {
        value = a.team > b.team ? 1 : -1;
      }
      else if(sort.sortParam == "positions") {
        value = a.position > b.position ? 1 : -1;
      }
      else {
        value = a.stats?.projection?.pitching[sort.sortParam] - b.stats?.projection?.pitching[sort.sortParam];
      }
      return sort.asc ? value : -value;
    }
    return [...players].sort(sortPitchers);
  }, [players, sort]);

  const filteredPlayers = useMemo(() => {
    if (!deferredMlbOnly) return sortedPlayers;
    return sortedPlayers.filter((p) => p.fantasyPositions?.includes("P"));
  }, [sortedPlayers, deferredMlbOnly]);

  const totalPages = Math.max(1, Math.ceil(filteredPlayers.length / PAGE_SIZE));
  const visiblePlayers = filteredPlayers.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const statColumns = (PITCHER_STAT_KEYS).toSorted();

  function handleSort(newSort : string) {
    let newAsc = sort.asc;
    if (newSort as SortParamPitcher == sort.sortParam) newAsc = !newAsc;
    setSort({sortParam: newSort as SortParamPitcher, asc: newAsc});
    setPage(1);
  }

  return(
    <div className="bg-gray-600 rounded-lg border border-zinc-800 overflow-hidden">
      <div className="flex flex-wrap gap-2 px-3 py-2 bg-gray-700 border-b border-zinc-800">
        <button
          onClick={() => { setMlbOnly((prev) => !prev); setPage(1); }}
          className={`px-2 py-0.5 rounded text-xs font-semibold border transition-colors ${
            mlbOnly
              ? "bg-blue-500 border-blue-400 text-white"
              : "bg-gray-600 border-zinc-600 text-zinc-300 hover:border-blue-400 hover:text-white"
          }`}
        >
          P
        </button>
      </div>
      <table className="w-full table-auto text-base text-left border-collapse">
        <thead className="bg-gray-500 text-black uppercase cursor-pointer">
          <tr>
            <th key="name" className={firstHeaderCellClass} style={firstCellStyle} onClick={() => handleSort("name")}>Name<SortIcon curSort={sort.sortParam} columnKey="name" asc={sort.asc}/></th>
            <th key="team" className={headerCellClass} onClick={() => handleSort("team")}>Team<SortIcon curSort={sort.sortParam} columnKey="team" asc={sort.asc}/></th>
            <th key="positions" className={headerCellClass} onClick={() => handleSort("positions")}>Position<SortIcon curSort={sort.sortParam} columnKey="positions" asc={sort.asc}/></th>
            {statColumns.map((statName) => (
              <th key={statName} className={headerCellClass} onClick={() => handleSort(statName)}>{statName}<SortIcon curSort={sort.sortParam} columnKey={statName} asc={sort.asc}/></th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-zinc-800">
          {visiblePlayers.map((player) => (
            <tr
              key={player.id}
              className="hover:bg-blue-800 cursor-pointer"
              onClick={() => router.push(`/players/${player.id}`)}
            >
              <td className={firstBodyCellClass} style={firstCellStyle}>{player.name}</td>
              <td className={bodyCellClass}>{player.team}</td>
              <td className={bodyCellClass}>{player.mlbPositions?.join(", ") || "-"}</td>
              {statColumns.map((statName) => (
                <td key={`${player.id}-${statName}`} className={bodyCellClass}>
                  {player.stats?.projection?.pitching[statName as keyof(PitcherStats)] ?? '-'}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      <div className="px-3 py-2 bg-gray-700 border-t border-zinc-800 text-white">
        <Pagination
          currentPage={page}
          totalPages={totalPages}
          total={filteredPlayers.length}
          onNext={() => setPage((p) => p + 1)}
          onPrev={() => setPage((p) => p - 1)}
        />
      </div>
    </div>
  )
}

function HittersTable({ players }: { players: HitterPlayer[] }) {
  const router = useRouter();

  const [sort, setSort] = useState<{ sortParam: SortParamHitter, asc: SortAsc }>({ sortParam: "ab", asc: true });
  const [selectedPositions, setSelectedPositions] = useState<RosterSlot[]>([]);
  const [page, setPage] = useState(1);
  const deferredPositions = useDeferredValue(selectedPositions);

  

  const sortedPlayers = useMemo(() => {
    function sortHitters(a: HitterPlayer, b: HitterPlayer) {
      let value: number;
      if (sort.sortParam == "name") {
        value = a.name > b.name ? 1 : -1;
      } else if (sort.sortParam == "team") {
        value = a.team > b.team ? 1 : -1;
      } else if (sort.sortParam == "positions") {
        value = a.position > b.position ? 1 : -1;
      } else {
        value = a.stats?.projection?.hitting[sort.sortParam] - b.stats?.projection?.hitting[sort.sortParam];
      }
      return sort.asc ? value : -value;
    }

    return [...players].sort(sortHitters);
  }, [players, sort]);

  const filteredPlayers = useMemo(() => {
    if (!deferredPositions.length) return sortedPlayers;
    return sortedPlayers.filter((p) =>
      p.fantasyPositions?.some((pos) => deferredPositions.includes(pos))
    );
  }, [sortedPlayers, deferredPositions]);

  const totalPages = Math.max(1, Math.ceil(filteredPlayers.length / PAGE_SIZE));
  const visiblePlayers = filteredPlayers.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const statColumns = (HITTER_STAT_KEYS).toSorted();

  function handleSort(newSort: string) {
    let newAsc = sort.asc;
    if (newSort as SortParamHitter == sort.sortParam) newAsc = !newAsc;
    setSort({ sortParam: newSort as SortParamHitter, asc: newAsc });
    setPage(1);
  }

  function togglePosition(pos: RosterSlot) {
    setSelectedPositions((prev) => prev.includes(pos) ? prev.filter((p) => p !== pos) : [...prev, pos]);
    setPage(1);
  }

  return (
    <div className="bg-gray-600 rounded-lg border border-zinc-800 overflow-hidden">
      <PositionFilterChips positions={HITTER_FILTER_POSITIONS} selected={selectedPositions} onToggle={togglePosition} />
      <table className="w-full table-auto text-base text-left border-collapse">
        <thead className="bg-gray-500 text-black uppercase cursor-pointer">
          <tr>
            <th key="name" className={firstHeaderCellClass} style={firstCellStyle} onClick={() => handleSort("name")}>Name<SortIcon curSort={sort.sortParam} columnKey="name" asc={sort.asc}/></th>
            <th key="team" className={headerCellClass} onClick={() => handleSort("team")}>Team<SortIcon curSort={sort.sortParam} columnKey="team" asc={sort.asc}/></th>
            <th key="positions" className={headerCellClass} onClick={() => handleSort("positions")}>Position<SortIcon curSort={sort.sortParam} columnKey="positions" asc={sort.asc}/></th>
            {statColumns.map((statName) => (
              <th key={statName} className={headerCellClass} onClick={() => handleSort(statName)}>{statName}<SortIcon curSort={sort.sortParam} columnKey={statName} asc={sort.asc}/></th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-zinc-800">
          {visiblePlayers.map((player) => (
            <tr
              key={player.id}
              className="hover:bg-blue-800 cursor-pointer"
              onClick={() => router.push(`/players/${player.id}`)}
            >
              <td className={firstBodyCellClass} style={firstCellStyle}>{player.name}</td>
              <td className={bodyCellClass}>{player.team}</td>
              <td className={bodyCellClass}>{player.fantasyPositions?.join(", ") || player.position}</td>
              {statColumns.map((statName) => (
                <td key={`${player.id}-${statName}`} className={bodyCellClass}>
                  {player.stats?.projection?.hitting[statName as keyof HitterStats] ?? '-'}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      <div className="px-3 py-2 bg-gray-700 border-t border-zinc-800 text-white">
        <Pagination
          currentPage={page}
          totalPages={totalPages}
          total={filteredPlayers.length}
          onNext={() => setPage((p) => p + 1)}
          onPrev={() => setPage((p) => p - 1)}
        />
      </div>
    </div>
  );
}
